### ISSUE TITLE
Resnet output doesn't match the FPN_FEAT_STRIDES

### ISSUE THREAD

**Issue by destinyzs** [jwyang/fpn.pytorch#12]
The default cnn network is res101.
However, on the [fpn.py line 184](https://github.com/jwyang/fpn.pytorch/blob/master/lib/model/fpn/fpn.py#L184), the size of `p2, p3, p4, p5, p6` are 1/4,1/8,1/16,1/16,1/32 of the input image's size, so the `FPN_FEAT_STRIDES` should be `[4,8,16,16,32]`.
But on the [trainval_net.py line 173](https://github.com/jwyang/fpn.pytorch/blob/master/trainval_net.py#L173), default `FPN_FEAT_STRIDES` is `[4, 8, 16, 32, 64]`, the config and code don't match.
I not sure whether the result will be affected, but i think you can modify it. @jwyang

**Comment by cjxnew** [comment]
Good suggestion brother, but I guess the author is not deal with this project any more......

**Comment by destinyzs** [comment]
yeah... so i will close this issue
