### ISSUE TITLE
Cuda Error: invalid argument nms_cuda_kernel.cu

### ISSUE THREAD

**Issue by ljtruong** [jwyang/fpn.pytorch#18]
I'm experiencing a CUDA error when running the scripts. 
There errors occurs [here](https://github.com/jwyang/fpn.pytorch/blob/23bd1d2fa09fbb9453f11625d758a61b9d600942/lib/model/nms/src/nms_cuda_kernel.cu#L147).  in lib/model/nms/src/nms_cuda_kernel.cu. 
The error is: 
CUDA Error: invalid argument, at line 147
CUDA Error: invalid argument, at line 154
which I assuming is referring to the line in the nms cuda kernel.

When executing nms in this [line](https://github.com/jwyang/fpn.pytorch/blob/23bd1d2fa09fbb9453f11625d758a61b9d600942/lib/model/rpn/proposal_layer_fpn.py#L111), of lib/model/rpn/proposal_layer_fpn.py
nms(torch.cat((proposals_single, scores_single), 1), nms_thresh). 

as a check, I have ensured in the make.sh file I changed compute to my gtx1080. I'm using pytorch 0.4 with python 2.7.

I haven't worked with cuda files before so I'm not too sure how to solve this.

**Comment by tyyyang** [comment]
add --cuda flag when running test_net

**Comment by ljtruong** [comment]
Solved.

**Comment by Karthik-Suresh93** [comment]
Hi, I added the --cuda flag but still the problem continues. Can you please elaborate on the solution @Worulz @skyoung @jwyang ?
